/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as MakalelerRouteImport } from './routes/makaleler'
import { Route as MakaleSlugRouteImport } from './routes/makale.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const MakalelerRoute = MakalelerRouteImport.update({
  id: '/makaleler',
  path: '/makaleler',
  getParentRoute: () => rootRouteImport,
} as any)
const MakaleSlugRoute = MakaleSlugRouteImport.update({
  id: '/makale/$slug',
  path: '/makale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kvkk': typeof KvkkRoute
  '/makaleler': typeof MakalelerRoute
  '/makale/$slug': typeof MakaleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kvkk': typeof KvkkRoute
  '/makaleler': typeof MakalelerRoute
  '/makale/$slug': typeof MakaleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kvkk': typeof KvkkRoute
  '/makaleler': typeof MakalelerRoute
  '/makale/$slug': typeof MakaleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/kvkk' | '/makaleler' | '/makale/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/kvkk' | '/makaleler' | '/makale/$slug'
  id: '__root__' | '/' | '/admin' | '/kvkk' | '/makaleler' | '/makale/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KvkkRoute: typeof KvkkRoute
  MakalelerRoute: typeof MakalelerRoute
  MakaleSlugRoute: typeof MakaleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makaleler': {
      id: '/makaleler'
      path: '/makaleler'
      fullPath: '/makaleler'
      preLoaderRoute: typeof MakalelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makale/$slug': {
      id: '/makale/$slug'
      path: '/makale/$slug'
      fullPath: '/makale/$slug'
      preLoaderRoute: typeof MakaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KvkkRoute: KvkkRoute,
  MakalelerRoute: MakalelerRoute,
  MakaleSlugRoute: MakaleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
